# Project information
site_name: 华师手册
site_url: https://scnusw.online
site_author: SCNU-SW-Online
site_description: Online Manual for SCNUer

# Repository
repo_url: https://github.com/SCNU-SW/SCNU-SW-Online
repo_name: SCNU-SW-Online

edit_uri: https://scnusw.online/edit-landing/?ref=

# Copyright
copyright: Copyright © 2024 华师手册

# Page tree
nav:
  - 简介:
    - 华师手册: index.md
    - 食用指南: intro/ug.md
    - 如何参与: intro/htc.md
    - 格式手册: intro/format.md
    - 致谢: intro/ack.md
    # - 关于: intro/about.md
  - 校历:
    - 2024-2025: calendar/24-25.md
  - 黄页:
    - 黄页: contact/index.md
  - 校园学习:
    - 校园学习: study/index.md
    # - 行知书院:
    - 数据科学与工程学院:
      - 课程学习: study/dse/course.md
      - 生涯规划: 
        - 考研篇: study/dse/pgexam.md
        - 保研篇: study/dse/pgrec.md
      - 工具软件:
        - LaTeX 入门: study/dse/latex.md
        - Git: study/dse/git.md
      - 竞赛:
        # - 数学建模: study/dse/sxjm.md
        - 算法竞赛: 
          - 学习路线: study/dse/roadmap.md
          - 学习资源: study/dse/resources.md
      #     - 蓝桥杯: study/dse/lanqiao.md
      # - 科研项目: study/dse/research.md
    # - 材料与新能源学院:
    # - 职业教育学院:
    # - 基础教育学院:
    - 商学院:
      - 现代密码学题库: study/ft/CryptQB.md
    # - 创意设计学院:
  # - 校园生活:
  #   - 校园生活: life/index.md
  - 社团活动:
    - 社团活动: organizations/index.md
  # - 关于实习:
  #   - 经验之谈: internship/index.md


# Configuration
theme:
  name: material
  custom_dir: overrides
  language: zh

  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil
    logo: material/bookshelf
  
  favicon: favicon.ico
  
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
    - content.action.edit
    - content.code.copy

  font:
    text: Fira Sans
    code: Fira Code


# Extensions
markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {}
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true


# Plugins
plugins:
  - search:
      lang:
        - zh
        - en
        - ja


extra_css:
  - stylesheets/extra.css


extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.zhimg.com/mathjax@3/es5/tex-mml-chtml.js
  # - https://mirrors.sustech.edu.cn/cdnjs//ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js
  # - javascripts/analytics.js


# Additional configuration
extra:
  copyright: <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a>
  generator: false


