site_name: 华师手册
copyright: Copyright © 2023-2024 华师手册
repo_url: https://github.com/SCNU-SW/SCNU-SW-Online
repo_name: SCNU-SW-Online
edit_uri: https://scnusw.online/edit-landing/?ref=


nav:
  - 简介:
    - Getting Started: index.md



theme:
  name: material
  custom_dir: overrides
  language: zh

  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil
  
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  logo: images/scnu.png
  favicon: images/scnu.png

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
    - content.action.edit
    - content.code.copy

  font:
    text: Fira Sans
    code: Fira Mono


# Extensions
markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {}
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true


plugins:
  - search:
      lang:
        - zh
        - en
        - ja


extra_css:
  - stylesheets/extra.css


extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.bootcdn.net/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.min.js
  # - javascripts/analytics.js


extra:
  copyright: <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a>
  generator: false

