name: deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force
      - run: mkdocs build

      - name: Push to preview
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: ${{ secrets.REPO_SSH_URL }}
          BRANCH: preview
          FOLDER: site
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          SQUASH_HISTORY: true

      - name: Push to main
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: ${{ secrets.REPO_SSH_URL }}
          BRANCH: main
          FOLDER: site
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          SQUASH_HISTORY: true