name: preview

on:
  pull_request_target:
    branches:
      - main

permissions:
  contents: write

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: pip install mkdocs-material 
      - run: mkdocs build

      - name: Copy vercel.json
        run: cp vercel.json site/

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: ${{ secrets.REPO_SSH_URL }}
          BRANCH: preview
          FOLDER: site
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          SQUASH_HISTORY: true